<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up(): void
    {
        Schema::create('vital_signs', function (Blueprint $table) {
            $table->id();
            $table->float('temp')->nullable();
            $table->unsignedBigInteger('temp_unit_type')->nullable();
            $table->foreign('temp_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('sat')->nullable();
            $table->float('sitting_breathing_frequency')->nullable();
            $table->unsignedBigInteger('sitting_breathing_frequency_unit_type')->nullable();
            $table->foreign('sitting_breathing_frequency_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('sitting_heart_rate')->nullable();
            $table->unsignedBigInteger('sitting_heart_rate_unit_type')->nullable();
            $table->foreign('sitting_heart_rate_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('sitting_pas_right_arm')->nullable();
            $table->unsignedBigInteger('sitting_pas_right_arm_unit_type')->nullable();
            $table->foreign('sitting_pas_right_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('sitting_pad_right_arm')->nullable();
            $table->unsignedBigInteger('sitting_pad_right_arm_unit_type')->nullable();
            $table->foreign('sitting_pad_right_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('sitting_pas_left_arm')->nullable();
            $table->unsignedBigInteger('sitting_pas_left_arm_unit_type')->nullable();
            $table->foreign('sitting_pas_left_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('sitting_pad_left_arm')->nullable();
            $table->unsignedBigInteger('sitting_pad_left_arm_unit_type')->nullable();
            $table->foreign('sitting_pad_left_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('lying_down_breathing_frequency')->nullable();
            $table->unsignedBigInteger('lying_down_breathing_frequency_unit_type')->nullable();
            $table->foreign('lying_down_breathing_frequency_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('lying_down_heart_rate')->nullable();
            $table->unsignedBigInteger('lying_down_heart_rate_unit_type')->nullable();
            $table->foreign('lying_down_heart_rate_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('lying_down_pas_right_arm')->nullable();
            $table->unsignedBigInteger('lying_down_pas_right_arm_unit_type')->nullable();
            $table->foreign('lying_down_pas_right_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('lying_down_pad_right_arm')->nullable();
            $table->unsignedBigInteger('lying_down_pad_right_arm_unit_type')->nullable();
            $table->foreign('lying_down_pad_right_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('lying_down_pas_left_arm')->nullable();
            $table->unsignedBigInteger('lying_down_pas_left_arm_unit_type')->nullable();
            $table->foreign('lying_down_pas_left_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('lying_down_pad_left_arm')->nullable();
            $table->unsignedBigInteger('lying_down_pad_left_arm_unit_type')->nullable();
            $table->foreign('lying_down_pad_left_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('standing_breathing_frequency')->nullable();
            $table->unsignedBigInteger('standing_breathing_frequency_unit_type')->nullable();
            $table->foreign('standing_breathing_frequency_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('standing_heart_rate')->nullable();
            $table->unsignedBigInteger('standing_heart_rate_unit_type')->nullable();
            $table->foreign('standing_heart_rate_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('standing_pas_right_arm')->nullable();
            $table->unsignedBigInteger('standing_pas_right_arm_unit_type')->nullable();
            $table->foreign('standing_pas_right_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('standing_pad_right_arm')->nullable();
            $table->unsignedBigInteger('standing_pad_right_arm_unit_type')->nullable();
            $table->foreign('standing_pad_right_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('standing_pas_left_arm')->nullable();
            $table->unsignedBigInteger('standing_pas_left_arm_unit_type')->nullable();
            $table->foreign('standing_pas_left_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('standing_pad_left_arm')->nullable();
            $table->unsignedBigInteger('standing_pad_left_arm_unit_type')->nullable();
            $table->foreign('standing_pad_left_arm_unit_type')
                ->references('id')
                ->on('attributes')
                ->onUpdate('cascade')
                ->onDelete('cascade');
            $table->float('avg_pad')->nullable();
            $table->float('avg_pas')->nullable();

            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down(): void
    {
        Schema::dropIfExists('vital_signs');
    }
};
